package com.mobiquity.espressohelper.core.espresso.resultanalyzer

import com.mobiquity.espressohelper.core.common.OperationResultAnalyzer

interface EspressoOperationResultAnalyzer : OperationResultAnalyzer